In [1]:
import numpy as np

# Задаємо розмірність матриці
N = 5  # Кількість рядків
M = 4  # Кількість стовпців

# Генеруємо випадкову матрицю
A = np.random.rand(N, M)

# Знаходимо середні значення для кожного рядка
row_means = np.mean(A, axis=1)

# Знаходимо найнижче середнє значення
min_row_mean = np.min(row_means)

# Знаходимо індекс рядка з найнижчим середнім значенням
min_row_index = np.argmin(row_means)

# Виводимо матрицю та результати
print("Матриця A:")
print(A)
print("\nСередні значення для кожного рядка:")
print(row_means)
print(f"\nНайнижче середнє значення: {min_row_mean} (знаходиться в рядку {min_row_index})")
ult[1], z = {result[2]}


Матриця A:
[[0.58758854 0.46609525 0.67037425 0.52222097]
 [0.92549742 0.60121491 0.32780789 0.61557234]
 [0.18658096 0.63315057 0.3668675  0.80702914]
 [0.46460009 0.9509393  0.10659622 0.20176629]
 [0.54252206 0.08947303 0.6385807  0.05117522]]

Середні значення для кожного рядка:
[0.56156975 0.61752314 0.49840704 0.43097547 0.33043775]

Найнижче середнє значення: 0.33043775077084814 (знаходиться в рядку 4)


<class 'NameError'>: name 'result' is not defined