In [3]:
import numpy as np

# Задання матриці A
A = np.array([[2, 3, 1],
              [-1, 1, 0],
              [1, 2, -1]])

# Задання матриці B
B = np.array([[1, 2, 1],
              [0, 1, 2],
              [3, 1, 1]])

# Обчислення добутку AB
AB = np.dot(A, B)

# Обчислення добутку BA
BA = np.dot(B, A)

# Обчислення матриці C = AB - BA
C = AB - BA

print(C)


[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]
